### ISSUE TITLE
Calling start() seems to exit the program

### ISSUE THREAD

**Issue by sector-f** [knsd/daemonize#19]
Alright, this seems pretty strange. I've tried both my own program, and the example program from the documentation. As far as I can tell, the crate just doesn't work. Creating a new Daemonize does seem to work. PID files do get created. But when I call `start()`, nothing happens.

I tried using a `match` statement that would print different messages depending on if `start()` returned an `Ok` or an `Err`. What did it print? Absolutely nothing. It's as if the program just cleanly exits when `start()` is called.

Additionally, the closure specified with `privileged_action()` doesn't seem to be getting called.

Either I'm right and there's a problem, or I'm wrong and I'm completely misunderstanding how to use this crate. Hopefully you can tell me which one it is.

**Comment by droundy** [comment]
I'm seeing this also.  Does daemonize perhaps require that it be run as root?

**Comment by wfraser** [comment]
Yes, in the process of daemonizing, the original (foreground) process exits, and a copy of it runs in the background. The background process can't print anything because it is not attached to the terminal -- if it was, it wouldn't be a background process. The foreground process can't keep running because then you would have two instances of your program running, which is probably not what you want.

See:
https://github.com/knsd/daemonize/blob/b617c78abc977d5f1d2b17e0dd3bb6c104701287/src/lib.rs#L347
