### ISSUE TITLE
Daemonizing while daemon is running clears pidfile

### ISSUE THREAD

**Issue by narpfel** [knsd/daemonize#20]
Trying to start another instance of the same daemon while the old instance is still running results in a `DaemonizeError::LockPidfile`, but before that, the old pidfile is opened in mode `"w"`. This truncates the pidfile, so the PID is lost. Is this behaviour intended? If not, a possible solution would be to `fopen` the pidfile in mode `"a"`, then try to `flock` it, and call `rewind` if the lock is acquired.

**Comment by asmjmisc** [comment]
Hi, I ran into the same issue. I'm only learning Rust, so I can't provide or advise on a fix, but I'd be willing to work with someone on it, or test to confirm. I see that the issue is from October 9th and the project isn't getting a lot of updates (the crate on crates.io was last updated a year ago), but I think it would be better for there to be a patch for a PR that provides at least some alternative.
